import type { NextPage } from 'next';
import Head from 'next/head';
import { getSortedPostsData } from '../lib/posts'
// import Image from 'next/image';

import NavBar from '../components/Navbar';

export default function Home({allPostsData}:any) {
  return (
  <div>
    <Head>
      <title>Blog</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main>
      <NavBar />
      <ul>
          {allPostsData.map(({ id, date, title }:any) => (
            <li key={id}>
              {title}
              <br />
              {id}
              <br />
              {date}
            </li>
          ))}
        </ul>

      {/* <p>
        Get started by editing
        {' '}
        <code>pages/index.tsx</code>
      </p>

      <div>
        <a href="https://nextjs.org/docs">
          <h2>Documentation &rarr;</h2>
          <p>Find in-depth information about Next.js features and API.</p>
        </a>

        <a href="https://nextjs.org/learn">
          <h2>Learn &rarr;</h2>
          <p>Learn about Next.js in an interactive course with quizzes!</p>
        </a>

        <a href="https://github.com/vercel/next.js/tree/canary/examples">
          <h2>Examples &rarr;</h2>
          <p>Discover and deploy boilerplate example Next.js projects.</p>
        </a>

        <a href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app">
          <h2>Deploy &rarr;</h2>
          <p>
            Instantly deploy your Next.js site to a public URL with Vercel.
          </p>
        </a>
      </div> */}
    </main>

    {/* <footer>footer</footer> */}
  </div>)
};

export async function getStaticProps() {
  const allPostsData = getSortedPostsData()
  return {
    props: {
      allPostsData
    }
  }
}

