/* eslint-disable jsx-a11y/anchor-is-valid */
import Head from 'next/head';
import Link from 'next/link';
import getSortedPostsData from '../lib/posts';

import Date from '../components/Date';
import HomeWrapper from '../components/HomeWrapper';

export default function Home({ allPostsData }: any) {
  return (
    <div>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeWrapper>
        <div className="space-y-2">
          {allPostsData.map(({ id, date, title }: any) => (
            <div key={id}>
              <Link href={`/posts/${id}`}>
                <a className="underline">{title}</a>
              </Link>
              <span className="pl-2">
                <Date dateString={date} />
              </span>
            </div>
          ))}
        </div>
      </HomeWrapper>
    </div>
  );
}

export async function getStaticProps() {
  const allPostsData = getSortedPostsData();
  return {
    props: {
      allPostsData,
    },
  };
}
